import { ProgramRulesConfig, RecommendedPlanSemester } from "@/types";

export const programRules: ProgramRulesConfig = {
  programId: "tu-darmstadt-msc-cs-dse",
  programLabel: "TU Darmstadt Computer Science M.Sc.",
  specializationLabel: "Data Science and Engineering",
  totalCredits: 120,
  legalDisclaimer:
    "Rules are modeled based on the English translation and confirmed understanding. Final decisions should be verified with the study office/examination board.",
  categoryGroups: [
    { id: "elective-specialization", label: "A. Elective Areas & Specializations" },
    { id: "general-education", label: "B. General Education" },
    { id: "thesis", label: "Master Thesis" },
  ],
  categories: [
    { id: "core-course-catalogues", label: "A.1 Core Course Catalogues", groupId: "elective-specialization" },
    { id: "specialization-dse", label: "A.2 Data Science and Engineering", groupId: "elective-specialization" },
    { id: "studium-generale", label: "General Education", groupId: "general-education" },
    { id: "master-thesis", label: "Master Thesis", groupId: "thesis" },
  ],
  subcategories: [
    {
      id: "basic-software-hardware",
      label: "Software & Hardware",
      categoryId: "core-course-catalogues",
    },
    { id: "basic-theory", label: "Theory", categoryId: "core-course-catalogues" },
    {
      id: "dse-foundations",
      label: "Foundations of Data Science",
      categoryId: "specialization-dse",
    },
    {
      id: "dse-data-systems",
      label: "Data Systems Engineering",
      categoryId: "specialization-dse",
    },
    {
      id: "dse-applications",
      label: "Data Science Applications",
      categoryId: "specialization-dse",
    },
    { id: "dse-seminar", label: "Seminar", categoryId: "specialization-dse" },
    { id: "dse-lab-project", label: "Lab / Project Lab", categoryId: "specialization-dse" },
    {
      id: "dse-practical-lab-teaching",
      label: "Practical Lab in Teaching",
      categoryId: "specialization-dse",
    },
    {
      id: "dse-research-paper",
      label: "Research Paper",
      categoryId: "specialization-dse",
    },
    {
      id: "ge-languages",
      label: "Languages",
      categoryId: "studium-generale",
    },
    {
      id: "ge-humanities-social-economics",
      label: "Humanities / Social Science / Economics / Business",
      categoryId: "studium-generale",
    },
    {
      id: "ge-environment-engineering-natural",
      label: "Environmental Studies / Engineering / Natural Sciences",
      categoryId: "studium-generale",
    },
    { id: "master-thesis", label: "Master Thesis", categoryId: "master-thesis" },
  ],
  requirements: [
    {
      id: "total-degree",
      label: "M.Sc. Computer Science",
      unit: "cp",
      min: 120,
      max: 120,
      requirementKind: "degree",
      description: "TU Darmstadt awards the degree once 120 CP are achieved.",
    },
    {
      id: "elective-specialization",
      label: "A. Elective Areas & Specializations",
      unit: "cp",
      min: 66,
      max: 72,
      parentId: "total-degree",
      requirementKind: "area",
    },
    {
      id: "core-course-catalogues",
      label: "A.1 Core Course Catalogues",
      unit: "cp",
      min: 12,
      max: 18,
      parentId: "elective-specialization",
      requirementKind: "area",
      apbCatalogueType: "30-5",
      gradeSelectionScope: true,
    },
    {
      id: "basic-software-hardware",
      label: "Software & Hardware",
      unit: "cp",
      min: 6,
      max: 12,
      parentId: "core-course-catalogues",
      requirementKind: "basket",
      gradeSelectionScope: true,
    },
    {
      id: "basic-theory",
      label: "Theory",
      unit: "cp",
      min: 6,
      max: 12,
      parentId: "core-course-catalogues",
      requirementKind: "basket",
      gradeSelectionScope: true,
    },
    {
      id: "specialization-dse",
      label: "A.2 Specialization: Data Science and Engineering",
      unit: "cp",
      min: 54,
      max: 60,
      parentId: "elective-specialization",
      requirementKind: "area",
    },
    {
      id: "dse-elective-area",
      label: "Elective Areas inside Data Science and Engineering",
      unit: "cp",
      min: 42,
      max: 48,
      parentId: "specialization-dse",
      requirementKind: "area",
      apbCatalogueType: "30-5",
      gradeSelectionScope: true,
    },
    {
      id: "dse-foundations",
      label: "Foundations of Data Science",
      unit: "cp",
      min: 12,
      max: 24,
      parentId: "dse-elective-area",
      requirementKind: "basket",
      gradeSelectionScope: true,
    },
    {
      id: "dse-data-systems",
      label: "Data Systems Engineering",
      unit: "cp",
      min: 12,
      max: 24,
      parentId: "dse-elective-area",
      requirementKind: "basket",
      gradeSelectionScope: true,
    },
    {
      id: "dse-applications",
      label: "Data Science Applications",
      unit: "cp",
      min: 12,
      max: 24,
      parentId: "dse-elective-area",
      requirementKind: "basket",
      gradeSelectionScope: true,
    },
    {
      id: "dse-practice-block",
      label: "Seminars, Labs, Practical Labs in Teaching",
      unit: "cp",
      min: 12,
      max: 18,
      parentId: "specialization-dse",
      requirementKind: "area",
      apbCatalogueType: "30-6",
      gradeSelectionScope: true,
    },
    {
      id: "dse-seminar",
      label: "Seminar",
      unit: "cp",
      min: 3,
      max: 12,
      minModules: 1,
      parentId: "dse-practice-block",
      requirementKind: "basket",
      description: "Minimum one seminar.",
      gradeSelectionScope: true,
    },
    {
      id: "dse-lab-project",
      label: "Lab / Project Lab",
      unit: "cp",
      min: 6,
      max: 15,
      minModules: 1,
      parentId: "dse-practice-block",
      requirementKind: "basket",
      description: "Minimum one lab, project lab, or similar course.",
      gradeSelectionScope: true,
    },
    {
      id: "dse-practical-lab-teaching",
      label: "Practical Lab in Teaching",
      unit: "cp",
      min: 0,
      max: 5,
      maxModules: 1,
      parentId: "dse-practice-block",
      requirementKind: "basket",
      description: "Optional and limited to one.",
      gradeSelectionScope: true,
    },
    {
      id: "dse-research-paper",
      label: "Research Paper",
      unit: "cp",
      min: 0,
      max: 9,
      parentId: "dse-practice-block",
      requirementKind: "basket",
      description: "Optional.",
      gradeSelectionScope: true,
    },
    {
      id: "studium-generale",
      label: "B. General Education",
      unit: "cp",
      min: 18,
      max: 24,
      parentId: "total-degree",
      requirementKind: "area",
      apbCatalogueType: "30-6",
      description:
        "Courses should come from TU Darmstadt catalogues outside Computer Science unless otherwise allowed.",
      gradeSelectionScope: true,
    },
    {
      id: "ge-languages",
      label: "Languages",
      unit: "cp",
      min: 0,
      max: 24,
      parentId: "studium-generale",
      requirementKind: "basket",
      gradeSelectionScope: true,
    },
    {
      id: "ge-humanities-social-economics",
      label: "Humanities / Social Science / Economics / Business",
      unit: "cp",
      min: 0,
      max: 24,
      parentId: "studium-generale",
      requirementKind: "basket",
      gradeSelectionScope: true,
    },
    {
      id: "ge-environment-engineering-natural",
      label: "Environmental Studies / Engineering / Natural Sciences",
      unit: "cp",
      min: 0,
      max: 24,
      parentId: "studium-generale",
      requirementKind: "basket",
      gradeSelectionScope: true,
    },
    {
      id: "master-thesis",
      label: "Master Thesis Computer Science",
      unit: "cp",
      min: 30,
      max: 30,
      parentId: "total-degree",
      requirementKind: "thesis",
      description: "30 CP, 900 hours, 26 weeks, graded.",
    },
  ],
};

export const recommendedPlan: RecommendedPlanSemester[] = [
  {
    id: "recommended-1",
    label: "Recommended Semester 1",
    suggestedCredits: 30,
    focus: "Start Core requirements and one DSE elective basket.",
    requirementIds: ["basic-software-hardware", "basic-theory", "dse-foundations"],
  },
  {
    id: "recommended-2",
    label: "Recommended Semester 2",
    suggestedCredits: 30,
    focus: "Continue DSE electives and begin General Education.",
    requirementIds: ["dse-data-systems", "dse-applications", "studium-generale"],
  },
  {
    id: "recommended-3",
    label: "Recommended Semester 3",
    suggestedCredits: 30,
    focus: "Finish specialization coursework and complete the seminar/lab block.",
    requirementIds: ["dse-elective-area", "dse-practice-block", "studium-generale"],
  },
  {
    id: "recommended-4",
    label: "Recommended Semester 4",
    suggestedCredits: 30,
    focus: "Focus on the Master Thesis and any remaining open CP.",
    requirementIds: ["master-thesis"],
  },
];
